language: objective-c
osx_image: xcode9
env:
    global:
    - PROJECT=Framezilla.xcodeproj
    - IOS_FRAMEWORK_SCHEME="Framezilla iOS"
    - IOS_SDK=iphonesimulator11.0
    matrix:
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"
    - DESTINATION="OS=11.0,name=iPhone 7 Plus"

script:
    - set -o pipefail
    - xcodebuild -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" build test | xcpretty -c --test --color
